# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tcpUdpSerialportTool.ui'
#
# Created: Tue Nov 21 19:37:44 2017
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TcpUdpComTool(object):
    def setupUi(self, TcpUdpComTool):
        TcpUdpComTool.setObjectName("TcpUdpComTool")
        TcpUdpComTool.resize(655, 494)
        self.pushButtonStart = QtWidgets.QPushButton(TcpUdpComTool)
        self.pushButtonStart.setGeometry(QtCore.QRect(500, 50, 141, 31))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.plainTextEditRec = QtWidgets.QPlainTextEdit(TcpUdpComTool)
        self.plainTextEditRec.setGeometry(QtCore.QRect(10, 10, 481, 261))
        self.plainTextEditRec.setObjectName("plainTextEditRec")
        self.plainTextEditSend = QtWidgets.QPlainTextEdit(TcpUdpComTool)
        self.plainTextEditSend.setGeometry(QtCore.QRect(10, 280, 481, 171))
        self.plainTextEditSend.setObjectName("plainTextEditSend")
        self.comboBoxStyle = QtWidgets.QComboBox(TcpUdpComTool)
        self.comboBoxStyle.setGeometry(QtCore.QRect(500, 10, 141, 31))
        self.comboBoxStyle.setObjectName("comboBoxStyle")
        self.frameStatus = QtWidgets.QFrame(TcpUdpComTool)
        self.frameStatus.setGeometry(QtCore.QRect(10, 458, 191, 21))
        self.frameStatus.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameStatus.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameStatus.setObjectName("frameStatus")
        self.labelStatusTag = QtWidgets.QLabel(self.frameStatus)
        self.labelStatusTag.setGeometry(QtCore.QRect(10, 0, 61, 21))
        self.labelStatusTag.setObjectName("labelStatusTag")
        self.labelStatus = QtWidgets.QLabel(self.frameStatus)
        self.labelStatus.setGeometry(QtCore.QRect(66, 0, 121, 21))
        self.labelStatus.setObjectName("labelStatus")
        self.comboBoxClientList = QtWidgets.QComboBox(TcpUdpComTool)
        self.comboBoxClientList.setGeometry(QtCore.QRect(500, 90, 141, 22))
        self.comboBoxClientList.setObjectName("comboBoxClientList")
        self.groupBox = QtWidgets.QGroupBox(TcpUdpComTool)
        self.groupBox.setGeometry(QtCore.QRect(500, 180, 141, 81))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton16 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton16.setGeometry(QtCore.QRect(10, 4, 71, 21))
        self.radioButton16.setObjectName("radioButton16")
        self.radioButtonString = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonString.setGeometry(QtCore.QRect(73, 4, 61, 21))
        self.radioButtonString.setObjectName("radioButtonString")
        self.pushButtonSend = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonSend.setGeometry(QtCore.QRect(10, 30, 121, 41))
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.checkBoxHexRec = QtWidgets.QCheckBox(TcpUdpComTool)
        self.checkBoxHexRec.setGeometry(QtCore.QRect(210, 460, 91, 20))
        self.checkBoxHexRec.setObjectName("checkBoxHexRec")
        self.groupBoxLocal = QtWidgets.QGroupBox(TcpUdpComTool)
        self.groupBoxLocal.setGeometry(QtCore.QRect(500, 300, 141, 71))
        self.groupBoxLocal.setFlat(False)
        self.groupBoxLocal.setObjectName("groupBoxLocal")
        self.lineEditPortLocal = QtWidgets.QLineEdit(self.groupBoxLocal)
        self.lineEditPortLocal.setGeometry(QtCore.QRect(50, 44, 81, 20))
        self.lineEditPortLocal.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditPortLocal.setObjectName("lineEditPortLocal")
        self.comboBoxLocal = QtWidgets.QComboBox(self.groupBoxLocal)
        self.comboBoxLocal.setGeometry(QtCore.QRect(10, 16, 121, 22))
        self.comboBoxLocal.setObjectName("comboBoxLocal")
        self.groupBoxAim = QtWidgets.QGroupBox(TcpUdpComTool)
        self.groupBoxAim.setGeometry(QtCore.QRect(500, 380, 141, 71))
        self.groupBoxAim.setObjectName("groupBoxAim")
        self.lineEditPortAim = QtWidgets.QLineEdit(self.groupBoxAim)
        self.lineEditPortAim.setGeometry(QtCore.QRect(50, 45, 81, 20))
        self.lineEditPortAim.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditPortAim.setObjectName("lineEditPortAim")
        self.lineEditIpAim = QtWidgets.QLineEdit(self.groupBoxAim)
        self.lineEditIpAim.setGeometry(QtCore.QRect(10, 20, 121, 20))
        self.lineEditIpAim.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditIpAim.setObjectName("lineEditIpAim")
        self.toolButtonShortCut = QtWidgets.QToolButton(TcpUdpComTool)
        self.toolButtonShortCut.setGeometry(QtCore.QRect(310, 453, 71, 31))
        self.toolButtonShortCut.setAutoRaise(True)
        self.toolButtonShortCut.setObjectName("toolButtonShortCut")
        self.pushButtonClearRec = QtWidgets.QPushButton(TcpUdpComTool)
        self.pushButtonClearRec.setGeometry(QtCore.QRect(510, 270, 121, 23))
        self.pushButtonClearRec.setObjectName("pushButtonClearRec")
        self.comboComNum = QtWidgets.QComboBox(TcpUdpComTool)
        self.comboComNum.setGeometry(QtCore.QRect(500, 122, 69, 22))
        self.comboComNum.setObjectName("comboComNum")
        self.comboBoxBaud = QtWidgets.QComboBox(TcpUdpComTool)
        self.comboBoxBaud.setGeometry(QtCore.QRect(572, 123, 69, 22))
        self.comboBoxBaud.setObjectName("comboBoxBaud")

        self.retranslateUi(TcpUdpComTool)
        QtCore.QMetaObject.connectSlotsByName(TcpUdpComTool)

    def retranslateUi(self, TcpUdpComTool):
        _translate = QtCore.QCoreApplication.translate
        TcpUdpComTool.setWindowTitle(_translate("TcpUdpComTool", "Widget"))
        self.pushButtonStart.setText(_translate("TcpUdpComTool", "连接"))
        self.labelStatusTag.setText(_translate("TcpUdpComTool", "当前状态:"))
        self.labelStatus.setText(_translate("TcpUdpComTool", "未连接"))
        self.radioButton16.setText(_translate("TcpUdpComTool", "16进制"))
        self.radioButtonString.setText(_translate("TcpUdpComTool", "字符串"))
        self.pushButtonSend.setToolTip(_translate("TcpUdpComTool", "ctrl+Enter"))
        self.pushButtonSend.setText(_translate("TcpUdpComTool", "发送"))
        self.checkBoxHexRec.setText(_translate("TcpUdpComTool", "Hex接收显示"))
        self.groupBoxLocal.setTitle(_translate("TcpUdpComTool", "本地"))
        self.groupBoxAim.setTitle(_translate("TcpUdpComTool", "目的"))
        self.toolButtonShortCut.setText(_translate("TcpUdpComTool", "快捷键"))
        self.pushButtonClearRec.setText(_translate("TcpUdpComTool", "清空接收框"))

